[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.0"
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true


